---
- name: "Upload file {{ filename }}"
  hosts: "{{ host }}"
  become: yes
  tasks:
    - name: Copy 
      ansible.builtin.copy:
        src: "/tmp/upload/{{ filename }}"
        dest: "{{ path_dest }}/{{ filename }}"