---
- name: Webserver deploy
  hosts: all
  become: yes
  tasks:
    - name: Copy *.war
      ansible.builtin.copy:
        src: "/tmp/{{ war_filename }}"
        dest: "/tmp/{{ war_filename }}.46.1.0.war"