---
# Descarga de los em.properties
- name: Backup files
  hosts: "{{host_bck}}"
  become: yes
  tasks:
    - name: Download *.war 
      ansible.builtin.fetch:
        src: "{{ path_dest }}{{ war_filename }}.war"
        dest: "{{ path_bck }}{{ war_filename }}.war.{{ bck_ver }}"
        flat: yes
        
- name: Webserver deploy
  hosts: all
  become: yes
  tasks:
    - name: Stop tomcat services
      ansible.builtin.service:
        name: tomcat
        state: stopped 

    - name: Delete all *.war
      ansible.builtin.file:
        dest: "{{path_dest}}{{ war_filename }}.war"
        state: absent
      ansible.builtin.file:
        dest: "{{path_dest}}{{ war_filename }}"
        state: absent

    - name: Copy *.war
      ansible.builtin.copy:
        src: "/tmp/{{ war_filename }}.war"
        dest: "{{ path_dest }}{{ war_filename }}.war"

    - name: Start tomcat services
      ansible.builtin.service:
        name: tomcat
        state: started 
#subir los em.properties
#actualizar la version con el modulo replace
#Reiniciar el tomcat 