---
- name: Backup files
  hosts: "{{host_bck}}"
  become: yes
  tasks:
    - name: Download *.war 
      ansible.builtin.fetch:
        src: "{{ path_dest }}{{ war_filename }}"
        dest: "{{ path_bck }}{{ war_filename }}.{{ bck_ver }}"
        flat: yes
        
- name: Webserver deploy
  hosts: all
  become: yes
  tasks:
    - name: Stop tomcat services
      ansible.builtin.service:
        name: tomcat
        state: stopped 

    - name: Delete all *.war
      ansible.builtin.file:
        dest: "{{path_dest}}"
        state: absent

    - name: Copy *.war
      ansible.builtin.copy:
        src: "/tmp/{{ war_filename }}"
        dest: "{{ path_dest }}{{ war_filename }}"

    - name: Start tomcat services
      ansible.builtin.service:
        name: tomcat
        state: started 