---
- name: Cleanup logs
  hosts: all
  gather_facts: false
  tasks:
  - name: Delete files based on a pattern
    find:
      paths: /var/log/tomcat
      patterns: "{{ pattern }}"
    register: files_to_delete

  - name: Remove the identified files
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ files_to_delete.files }}"