---
- name: Cleanup logs
  hosts: all
  gather_facts: false
  tasks:
  - name: Collect files
    shell: find /var/log/tomcat -type f -mtime +3
    register: matched_files_dirs
    
  - name: Remove files
    become_user: root
    file: 
        path: /var/log/tomcat 
        state: absent
    with_items: "{{ matched_files_dirs.stdout_lines }}"