---
- name: VMware tools
  hosts: all
  remote_user: {{ user }}
  become: yes
  tasks:
    - name: Verificar si el módulo 'requests' está instalado
      command: pip show requests
      register: requests_module_info
      ignore_errors: yes

    - name: Instalar el módulo 'requests'
      pip:
        name: requests
      when: requests_module_info.rc != 0

    - name: Gather info about tag categories
      community.vmware.vmware_category_info:
      delegate_to: localhost
      register: all_tag_category_info