---
- name: Block web status
  block:
  - name: Request web status
    ansible.builtin.uri:
      url: "http://{{ ansible_all_ipv4_addresses[0] }}:{{ web_url }}"

  rescue:
  - name: Check tomcat service status
    become: true
    ansible.builtin.command: systemctl restart tomcat.service
    register: tomcat_status
    ignore_errors: true

  - name: Slack message
    ansible.builtin.include_tasks: Slack.yml
