---
- name: Block web status
  block:
  - name: Request web status
    ansible.builtin.uri:
      url: "http://{{ ansible_all_ipv4_addresses[0] }}:{{ web_url }}"

  rescue:
  - name: Check tomcat service status
    become: true
    ansible.builtin.command: systemctl status tomcat.service
    register: tomcat_status
    ignore_errors: true

  - name: Debug tomcat status
    ansible.builtin.debug:
      var: tomcat_status

  - name: Restart tomcat
    become: true
    become_user: root
    become_method: sudo
    ansible.builtin.service:
      name: tomcat
      state: restarted

  - name: Slack message
    ansible.builtin.include_tasks: Slack.yml
